name: ds-test-prophecy-project
description: testing the connection with github repo
version: 0.0.1
author: harshal@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: dstestprophecyproject
  parentArtefactID: harshalcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2023-10-31 13:30:35'
pipelines:
  pipelines/data_tets_pipeline_2:
    name: data_tets_pipeline_2
    description: ''
    author: harshal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-05 09:48:53'
    datasets:
      inputs:
      - datasets/input_data_set
      outputs:
      - datasets/output_data_set
    subgraphs: []
    dependencies: {}
datasets:
  datasets/input_data_set:
    name: input_data_set
    description: ''
    author: harshal@cloudaeon.net
    createdAt: '2023-11-05 09:51:22'
    mode: batch
    physicalDatasets:
      dev_ds:
        fabricId: 6419
        datasetType: File
        description: ''
        author: harshal@cloudaeon.net
        createdAt: '2023-11-05 09:51:22'
  datasets/output_data_set:
    name: output_data_set
    description: ''
    author: harshal@cloudaeon.net
    createdAt: '2023-11-05 09:58:40'
    mode: batch
    physicalDatasets:
      dev_ds:
        fabricId: 6419
        datasetType: File
        description: ''
        author: harshal@cloudaeon.net
        createdAt: '2023-11-05 09:58:40'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-11-05 09:47:52'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-10-31 13:29:56'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-31 13:29:56'
pipelineConfigurations: {}
